destination: "public/fme-connectors"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public]

ga_tracking_code: "REPLACEME"

title: Socrata Connectors
root: "/fme-connectors"
icon: fa fa-refresh
github_repo: https://github.com/socrata/fme-connectors
