destination: "public/connectors"
exclude: [Gemfile, Gemfile.lock, public, .ruby-*]
incremental: true

ga_tracking_code: "UA-9046230-12"

title: Socrata Connectors &amp; ETL Templates
baseurl: "/connectors"
icon: fa fa-refresh
github_repo: https://github.com/socrata/connectors
contribute: /connectors/contributing.html

local_js:
  - "/common/js/ga-tracking.js"
