destination: "public/connectors"
exclude: [Gemfile, Gemfile.lock, .rvmrc, public]

ga_tracking_code: "REPLACEME"

title: Socrata Connectors
root: "/connectors"
icon: fa fa-refresh
github_repo: https://github.com/socrata/connectors
